---
box2d-dev:
  ubuntu: [box2d] # Custom build of Box2D 2.3 as a shared library.
liblapacke:
  ubuntu: [liblapacke-dev]
mpfi:
  ubuntu: [libmpfi-dev]
newmat:
  ubuntu: [libnewmat10-dev]
openrave:
  ubuntu: [pr-openrave]
libopenthreads:
  ubuntu: [libopenthreads-dev]
python-hashlib:
  ubuntu: [hashlib]
python-trollius:
  ubuntu:
    pip: [trollius]
