---
liblapacke:
  ubuntu: [liblapacke-dev]
mpfi:
  ubuntu: [libmpfi-dev]
newmat:
  ubuntu: [libnewmat10-dev]
openrave:
  ubuntu: [pr-openrave]
libopenthreads:
  ubuntu: [libopenthreads-dev]
python-hashlib:
  ubuntu: [hashlib]
python-trollius:
  ubuntu:
    pip: [trollius]
openrave:
  ubuntu: [pr-openrave]
