---
liblapacke:
  ubuntu: [liblapacke-dev]
newmat:
  ubuntu: [libnewmat10-dev]
openrave:
  ubuntu: [pr-openrave]
libopenthreads:
  ubuntu: [libopenthreads-dev]
python-hashlib:
  ubuntu: [hashlib]
python-trollius:
  ubuntu: [python-trollius]
