---
box2d-dev: # Override; the default package installs a static lib.
  ubuntu: [box2d]
debsums: # Required by NASA packages.
  ubuntu: [debsums]
liblapacke:
  ubuntu: [liblapacke-dev]
mpfi:
  ubuntu: [libmpfi-dev]
newmat:
  ubuntu: [libnewmat10-dev]
nlopt: # Override; ros-indigo-nlopt is too old for DART.
  ubuntu: [libnlopt-dev]
openrave:
  ubuntu: [pr-openrave]
libopenthreads:
  ubuntu: [libopenthreads-dev]
python-hashlib:
  ubuntu: [hashlib]
python-protobuf: # Required by NASA packages.
  ubuntu: [python-protobuf]
python-trollius:
  ubuntu:
    pip: [trollius]
zeromq: # Required by NASA packages.
  ubuntu: [libzmq-dev]
