---
box2d-dev: # Custom build of Box2D 2.3 as a shared library.
  ubuntu: [box2d]
debsums: # Required by NASA packages.
  ubuntu: [debsums]
liblapacke:
  ubuntu: [liblapacke-dev]
mpfi:
  ubuntu: [libmpfi-dev]
newmat:
  ubuntu: [libnewmat10-dev]
openrave:
  ubuntu: [pr-openrave]
libopenthreads:
  ubuntu: [libopenthreads-dev]
python-hashlib:
  ubuntu: [hashlib]
python-protobuf: # Required by NASA packages.
  ubuntu: [python-protobuf]
python-trollius:
  ubuntu:
    pip: [trollius]
zeromq: # Required by NASA packages.
  ubuntu: [libzmq-dev]
