---
liblapacke:
  ubuntu:
    apt: [liblapacke-dev]
newmat:
  ubuntu:
    apt: [libnewmat10-dev]
openrave:
  ubuntu:
    apt: [pr-openrave]
python-hashlib:
  ubuntu:
    pip: [hashlib]
python-trollius:
  ubuntu:
    apt: [python-trollius]
